import { Theme } from "../theme.slint";

export component Chip inherits Rectangle {
    in property <string> label;
    in property <length> unit: 16px;

    height: 2.5 * root.unit;
    border-radius: self.height / 2;
    background: Theme.modal-background.with-alpha(0.6);
    border-width: 1px;
    border-color: Theme.overlay;

    Text {
        padding-left: root.unit;
        padding-right: root.unit;
        text: root.label;
        color: Theme.text-primary;
        opacity: 0.82;
        font-size: 0.95 * root.unit;
        font-weight: 600;
        horizontal-alignment: center;
        vertical-alignment: center;
        overflow: elide;
    }
}
