use slint::ComponentHandle;

use crate::{AppActions, MainWindow};

macro_rules! forward_action {
    ($ui:ident, $actions:ident, $on:ident, $invoke:ident $(, $arg:ident)*) => {{
        let weak_ui = $ui.as_weak();
        $actions.$on(move |$($arg),*| {
            if let Some(ui) = weak_ui.upgrade() {
                ui.$invoke($($arg),*);
            }
        });
    }};
}

/// Connects presentation-global actions to the stable MainWindow callback
/// contract. This replaces deprecated Slint callback aliases while keeping
/// the existing Rust model and callback modules unchanged.
pub fn install(ui: &MainWindow) {
    let actions = ui.global::<AppActions>();
    forward_action!(ui, actions, on_toggle_fullscreen, invoke_toggle_fullscreen);
    forward_action!(
        ui,
        actions,
        on_open_external_url,
        invoke_open_external_url,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_submit_login,
        invoke_submit_login,
        arg0,
        arg1
    );
    forward_action!(
        ui,
        actions,
        on_submit_register,
        invoke_submit_register,
        arg0,
        arg1,
        arg2,
        arg3,
        arg4
    );
    forward_action!(ui, actions, on_facebook_login, invoke_facebook_login);
    forward_action!(ui, actions, on_apple_login, invoke_apple_login);
    forward_action!(ui, actions, on_cancel_auth, invoke_cancel_auth);
    forward_action!(
        ui,
        actions,
        on_request_password_reset,
        invoke_request_password_reset,
        arg0
    );
    forward_action!(ui, actions, on_guest_login, invoke_guest_login);
    forward_action!(ui, actions, on_logout, invoke_logout);
    forward_action!(
        ui,
        actions,
        on_board_item_selected,
        invoke_board_item_selected,
        arg0,
        arg1,
        arg2
    );
    forward_action!(
        ui,
        actions,
        on_remove_continue_watching,
        invoke_remove_continue_watching,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_board_see_all_continue_watching,
        invoke_board_see_all_continue_watching
    );
    forward_action!(
        ui,
        actions,
        on_board_see_all_clicked,
        invoke_board_see_all_clicked,
        arg0,
        arg1,
        arg2
    );
    forward_action!(
        ui,
        actions,
        on_global_search_edited,
        invoke_global_search_edited,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_global_search_submitted,
        invoke_global_search_submitted,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_global_search_suggestion_selected,
        invoke_global_search_suggestion_selected,
        arg0,
        arg1
    );
    forward_action!(
        ui,
        actions,
        on_search_item_selected,
        invoke_search_item_selected,
        arg0,
        arg1,
        arg2
    );
    forward_action!(ui, actions, on_request_poster, invoke_request_poster, arg0);
    forward_action!(
        ui,
        actions,
        on_discover_type_changed,
        invoke_discover_type_changed,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_discover_catalog_changed,
        invoke_discover_catalog_changed,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_discover_genre_changed,
        invoke_discover_genre_changed,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_discover_search_changed,
        invoke_discover_search_changed,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_discover_item_selected,
        invoke_discover_item_selected,
        arg0
    );
    forward_action!(ui, actions, on_play_preview, invoke_play_preview);
    forward_action!(
        ui,
        actions,
        on_toggle_library_preview,
        invoke_toggle_library_preview
    );
    forward_action!(
        ui,
        actions,
        on_library_type_changed,
        invoke_library_type_changed,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_library_sort_changed,
        invoke_library_sort_changed,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_library_search_changed,
        invoke_library_search_changed,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_library_item_selected,
        invoke_library_item_selected,
        arg0,
        arg1
    );
    forward_action!(ui, actions, on_install_addon, invoke_install_addon, arg0);
    forward_action!(
        ui,
        actions,
        on_uninstall_addon,
        invoke_uninstall_addon,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_open_addon_details,
        invoke_open_addon_details,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_close_addon_details,
        invoke_close_addon_details
    );
    forward_action!(
        ui,
        actions,
        on_configure_addon,
        invoke_configure_addon,
        arg0
    );
    forward_action!(ui, actions, on_share_addon, invoke_share_addon, arg0);
    forward_action!(
        ui,
        actions,
        on_addons_search_changed,
        invoke_addons_search_changed,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_details_toggle_library,
        invoke_details_toggle_library
    );
    forward_action!(
        ui,
        actions,
        on_details_toggle_watched,
        invoke_details_toggle_watched
    );
    forward_action!(
        ui,
        actions,
        on_details_season_changed,
        invoke_details_season_changed,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_details_episode_changed,
        invoke_details_episode_changed,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_details_episode_search_changed,
        invoke_details_episode_search_changed,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_details_toggle_episode_watched,
        invoke_details_toggle_episode_watched,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_details_copy_stream_link,
        invoke_details_copy_stream_link,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_details_copy_magnet_link,
        invoke_details_copy_magnet_link,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_details_copy_download_link,
        invoke_details_copy_download_link,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_details_toggle_season_watched,
        invoke_details_toggle_season_watched,
        arg0
    );
    forward_action!(ui, actions, on_play_stream, invoke_play_stream, arg0);
    forward_action!(
        ui,
        actions,
        on_apply_cache_settings,
        invoke_apply_cache_settings,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_interface_language,
        invoke_settings_change_interface_language,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_ui_style,
        invoke_settings_change_ui_style,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_subtitles_language,
        invoke_settings_change_subtitles_language,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_torrent_profile,
        invoke_settings_change_torrent_profile,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_hardware_acceleration,
        invoke_settings_change_hardware_acceleration,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_clear_search_history,
        invoke_settings_clear_search_history
    );
    forward_action!(ui, actions, on_shutdown_server, invoke_shutdown_server);
    forward_action!(
        ui,
        actions,
        on_settings_change_seeding_enabled,
        invoke_settings_change_seeding_enabled,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_dht_enabled,
        invoke_settings_change_dht_enabled,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_pex_enabled,
        invoke_settings_change_pex_enabled,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_lsd_enabled,
        invoke_settings_change_lsd_enabled,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_refresh_logs,
        invoke_settings_refresh_logs
    );
    forward_action!(
        ui,
        actions,
        on_settings_open_logs_folder,
        invoke_settings_open_logs_folder
    );
    forward_action!(
        ui,
        actions,
        on_settings_export_data,
        invoke_settings_export_data
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_binge_watching,
        invoke_settings_change_binge_watching,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_discord_rpc_enabled,
        invoke_settings_change_discord_rpc_enabled,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_tidb_api_key,
        invoke_settings_change_tidb_api_key,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_tidb_show_intro,
        invoke_settings_change_tidb_show_intro,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_tidb_show_recap,
        invoke_settings_change_tidb_show_recap,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_tidb_show_credits,
        invoke_settings_change_tidb_show_credits,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_tidb_show_preview,
        invoke_settings_change_tidb_show_preview,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_hide_spoilers,
        invoke_settings_change_hide_spoilers,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_gamepad_support,
        invoke_settings_change_gamepad_support,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_play_in_background,
        invoke_settings_change_play_in_background,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_subtitles_auto_select,
        invoke_settings_change_subtitles_auto_select,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_subtitles_font,
        invoke_settings_change_subtitles_font,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_subtitles_size,
        invoke_settings_change_subtitles_size,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_subtitles_bold,
        invoke_settings_change_subtitles_bold,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_subtitles_offset,
        invoke_settings_change_subtitles_offset,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_seek_duration,
        invoke_settings_change_seek_duration,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_pause_on_minimize,
        invoke_settings_change_pause_on_minimize,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_settings_change_quit_on_close,
        invoke_settings_change_quit_on_close,
        arg0
    );
    forward_action!(ui, actions, on_tab_changed, invoke_tab_changed, arg0);
    forward_action!(ui, actions, on_navigation_back, invoke_navigation_back);
    forward_action!(
        ui,
        actions,
        on_navigation_forward,
        invoke_navigation_forward
    );
    forward_action!(ui, actions, on_calendar_previous, invoke_calendar_previous);
    forward_action!(ui, actions, on_calendar_next, invoke_calendar_next);
    forward_action!(
        ui,
        actions,
        on_calendar_item_selected,
        invoke_calendar_item_selected,
        arg0,
        arg1
    );
    forward_action!(
        ui,
        actions,
        on_player_toggle_pause,
        invoke_player_toggle_pause
    );
    forward_action!(ui, actions, on_player_seek, invoke_player_seek, arg0);
    forward_action!(
        ui,
        actions,
        on_player_seek_relative,
        invoke_player_seek_relative,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_player_change_volume,
        invoke_player_change_volume,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_player_toggle_mute,
        invoke_player_toggle_mute
    );
    forward_action!(
        ui,
        actions,
        on_player_change_subtitle,
        invoke_player_change_subtitle,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_player_change_audio,
        invoke_player_change_audio,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_player_skip_segment,
        invoke_player_skip_segment
    );
    forward_action!(
        ui,
        actions,
        on_player_change_subtitle_delay,
        invoke_player_change_subtitle_delay,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_player_change_subtitle_size,
        invoke_player_change_subtitle_size,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_player_change_subtitle_offset,
        invoke_player_change_subtitle_offset,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_player_change_speed,
        invoke_player_change_speed,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_player_change_video_scale,
        invoke_player_change_video_scale,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_player_copy_stream_link,
        invoke_player_copy_stream_link
    );
    forward_action!(
        ui,
        actions,
        on_player_download_video,
        invoke_player_download_video
    );
    forward_action!(
        ui,
        actions,
        on_player_play_episode,
        invoke_player_play_episode,
        arg0
    );
    forward_action!(
        ui,
        actions,
        on_player_toggle_fullscreen,
        invoke_player_toggle_fullscreen
    );
    forward_action!(ui, actions, on_player_close, invoke_player_close);
    forward_action!(ui, actions, on_player_activity, invoke_player_activity);
}
